In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
file_path = '/content/drive/MyDrive/FYP/English_Transcription_1122.csv'

# Read the CSV file
df = pd.read_csv(file_path)

# Print column names
print("Column Names:")
print(df.columns.tolist())

# Print number of records
print(f"\nNumber of records: {len(df)}")

Column Names:
['English_Translation']

Number of records: 1201

In [ ]:
#cleaned Transcription mean convert all text in lower case:

import re

# Define a function to clean the transcriptions
def clean_text(text):
    # Check if text is a string before applying lower()
    if isinstance(text, str):
        text = text.lower()  # Convert to lowercase
        text = re.sub(r'[^\w\s]', ' ', text)  # Remove punctuation and special characters
        text = re.sub(r'\d+', ' ', text)  # Remove digits
    # If not a string, return original value (or handle it differently)
    # For example, you could convert floats to strings:
    # elif isinstance(text, float):
    #     text = str(text)
    return text



# Apply the cleaning function to the correct column
df['Cleaned_Transcription'] = df['English_Translation'].apply(clean_text)

# Check cleaned transcriptions
df[['English_Translation', 'Cleaned_Transcription']].head()

,English_Translation,Cleaned_Transcription
0,Press A Press One for Ambulances in the Alaiku...,press a press one for ambulances in the alaiku...
1,Al -Alaikum Ji and Alaikum al -Islam are sayin...,al alaikum ji and alaikum al islam are sayin...
2,What is your name? This is a matter of locatio...,what is your name this is a matter of locatio...
3,Assalam Alaikum Rescue Double One Double Two E...,assalam alaikum rescue double one double two e...
4,Press A Press One for Ambulances in the Alaiku...,press a press one for ambulances in the alaiku...

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

# Ensure the necessary NLTK packages are downloaded
nltk.download('punkt')
nltk.download('punkt_tab') # Download the punkt_tab data package

# Define a function to handle non-string values
def safe_tokenize(text):
    if isinstance(text, str):
        return word_tokenize(text)
    else:
        # Handle non-string values (e.g., convert to string)
        return word_tokenize(str(text))

# Tokenize the cleaned transcriptions, handling non-string values
df['Tokenized_Transcription'] = df['Cleaned_Transcription'].apply(safe_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
# tokenized sentence : ['This', 'is', 'an', 'emergency', 'call']  Filtered sentence : ['emergency', 'call']

from nltk.corpus import stopwords

# Download NLTK stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Define a function to remove stopwords from tokenized text
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

# Apply the stopword removal function
df['Filtered_Transcription'] = df['Tokenized_Transcription'].apply(remove_stopwords)

# Check filtered transcriptions
df[['Tokenized_Transcription', 'Filtered_Transcription']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

,Tokenized_Transcription,Filtered_Transcription
0,"[press, a, press, one, for, ambulances, in, th...","[press, press, one, ambulances, alaikum, rescu..."
1,"[al, alaikum, ji, and, alaikum, al, islam, are...","[al, alaikum, ji, alaikum, al, islam, saying, ..."
2,"[what, is, your, name, this, is, a, matter, of...","[name, matter, location, marie, come, kaller, ..."
3,"[assalam, alaikum, rescue, double, one, double...","[assalam, alaikum, rescue, double, one, double..."
4,"[press, a, press, one, for, ambulances, in, th...","[press, press, one, ambulances, alaikum, rescu..."

In [ ]:
# Filtered: ['running', 'cars'] Lemmatized: ['run', 'car']

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Define a function to lemmatize the tokens
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(token) for token in tokens]

# Apply lemmatization
df['Lemmatized_Transcription'] = df['Filtered_Transcription'].apply(lemmatize_tokens)

# Check lemmatized transcriptions
df[['Filtered_Transcription', 'Lemmatized_Transcription']].head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

,Filtered_Transcription,Lemmatized_Transcription
0,"[press, press, one, ambulances, alaikum, rescu...","[press, press, one, ambulance, alaikum, rescue..."
1,"[al, alaikum, ji, alaikum, al, islam, saying, ...","[al, alaikum, ji, alaikum, al, islam, saying, ..."
2,"[name, matter, location, marie, come, kaller, ...","[name, matter, location, marie, come, kaller, ..."
3,"[assalam, alaikum, rescue, double, one, double...","[assalam, alaikum, rescue, double, one, double..."
4,"[press, press, one, ambulances, alaikum, rescu...","[press, press, one, ambulance, alaikum, rescue..."

In [ ]:
# Save the preprocessed data to a new CSV file
output_file = '/content/drive/MyDrive/FYP/preprocessed_transcriptions.csv'
df.to_csv(output_file, index=False)

print("Preprocessed data saved successfully. The file is saved as 'preprocessed_transcriptions.csv'")

Preprocessed data saved successfully. The file is saved as 'preprocessed_transcriptions.csv'

In [ ]:
from google.colab import files
files.download('/content/drive/MyDrive/FYP/preprocessed_transcriptions.csv')

In [ ]:
df.head(-1)

,English_Translation,Cleaned_Transcription,Tokenized_Transcription,Filtered_Transcription,Lemmatized_Transcription
0,Press A Press One for Ambulances in the Alaiku...,press a press one for ambulances in the alaiku...,"[press, a, press, one, for, ambulances, in, th...","[press, press, one, ambulances, alaikum, rescu...","[press, press, one, ambulance, alaikum, rescue..."
1,Al -Alaikum Ji and Alaikum al -Islam are sayin...,al alaikum ji and alaikum al islam are sayin...,"[al, alaikum, ji, and, alaikum, al, islam, are...","[al, alaikum, ji, alaikum, al, islam, saying, ...","[al, alaikum, ji, alaikum, al, islam, saying, ..."
2,What is your name? This is a matter of locatio...,what is your name this is a matter of locatio...,"[what, is, your, name, this, is, a, matter, of...","[name, matter, location, marie, come, kaller, ...","[name, matter, location, marie, come, kaller, ..."
3,Assalam Alaikum Rescue Double One Double Two E...,assalam alaikum rescue double one double two e...,"[assalam, alaikum, rescue, double, one, double...","[assalam, alaikum, rescue, double, one, double...","[assalam, alaikum, rescue, double, one, double..."
4,Press A Press One for Ambulances in the Alaiku...,press a press one for ambulances in the alaiku...,"[press, a, press, one, for, ambulances, in, th...","[press, press, one, ambulances, alaikum, rescu...","[press, press, one, ambulance, alaikum, rescue..."
...,...,...,...,...,...
1195,Short circuit caused fire at Faisal Avenue. Ne...,short circuit caused fire at faisal avenue ne...,"[short, circuit, caused, fire, at, faisal, ave...","[short, circuit, caused, fire, faisal, avenue,...","[short, circuit, caused, fire, faisal, avenue,..."
1196,There is an accident near Saddar. One person i...,there is an accident near saddar one person i...,"[there, is, an, accident, near, saddar, one, p...","[accident, near, saddar, one, person, injured]","[accident, near, saddar, one, person, injured]"
1197,My father is not breathing at Gulshan-e-Iqbal....,my father is not breathing at gulshan e iqbal ...,"[my, father, is, not, breathing, at, gulshan, ...","[father, breathing, gulshan, e, iqbal, please,...","[father, breathing, gulshan, e, iqbal, please,..."
1198,Man is vomiting blood at Bahria Town. Emergency!,man is vomiting blood at bahria town emergency,"[man, is, vomiting, blood, at, bahria, town, e...","[man, vomiting, blood, bahria, town, emergency]","[man, vomiting, blood, bahria, town, emergency]"
1199,Man is vomiting blood at Bahria Town. Emergency!,man is vomiting blood at bahria town emergency,"[man, is, vomiting, blood, at, bahria, town, e...","[man, vomiting, blood, bahria, town, emergency]","[man, vomiting, blood, bahria, town, emergency]"